name: mvvm_architecture_learn
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.15
  cupertino_icons: ^1.0.2
  file_picker: ^4.4.0
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  firebase_storage: ^10.2.16
  firebase_messaging: ^11.4.0
  flutter:
    sdk: flutter
  flutter_linkify: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutterfire_ui: ^0.4.1
  font_awesome_flutter: ^9.0.0
  image_picker: ^0.8.4+4
  import_sorter: ^4.6.0
  intl: ^0.17.0
  page_transition: ^2.0.5
  responsive_builder: ^0.4.2
  sentry_flutter: ^6.5.1
  url_launcher: ^6.0.20
  uuid: ^3.0.5
  video_player: ^2.4.2
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  freezed:
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

